-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reversi_accel_xfGaussianFilter3x3_16_1024_1024_3_16_1_2_2_10_1024_Pipeline_Col_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_in_data323_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    mat_in_data323_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_in_data323_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_in_data323_empty_n : IN STD_LOGIC;
    mat_in_data323_read : OUT STD_LOGIC;
    mat_blur_data324_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    mat_blur_data324_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_blur_data324_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_blur_data324_full_n : IN STD_LOGIC;
    mat_blur_data324_write : OUT STD_LOGIC;
    img_width : IN STD_LOGIC_VECTOR (15 downto 0);
    buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_ce1 : OUT STD_LOGIC;
    buf_V_we1 : OUT STD_LOGIC;
    buf_V_d1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    buf_V_17_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_17_ce0 : OUT STD_LOGIC;
    buf_V_17_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    buf_V_17_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_17_ce1 : OUT STD_LOGIC;
    buf_V_17_we1 : OUT STD_LOGIC;
    buf_V_17_d1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    buf_V_18_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_18_ce0 : OUT STD_LOGIC;
    buf_V_18_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    buf_V_18_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_18_ce1 : OUT STD_LOGIC;
    buf_V_18_we1 : OUT STD_LOGIC;
    buf_V_18_d1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    tp_V : IN STD_LOGIC_VECTOR (1 downto 0);
    mid_V : IN STD_LOGIC_VECTOR (1 downto 0);
    bottom_V : IN STD_LOGIC_VECTOR (1 downto 0);
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp_i_i200_i : IN STD_LOGIC_VECTOR (0 downto 0);
    p_Val2_125_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_125_out_ap_vld : OUT STD_LOGIC;
    p_Val2_124_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_124_out_ap_vld : OUT STD_LOGIC;
    p_Val2_123_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_123_out_ap_vld : OUT STD_LOGIC;
    p_Val2_122_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_122_out_ap_vld : OUT STD_LOGIC;
    p_Val2_121_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_121_out_ap_vld : OUT STD_LOGIC;
    p_Val2_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_out_ap_vld : OUT STD_LOGIC;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_din11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_dout0 : IN STD_LOGIC_VECTOR (7 downto 0);
    grp_xFapplygaussian3x3_16_s_fu_560_p_ce : OUT STD_LOGIC );
end;


architecture behav of reversi_accel_xfGaussianFilter3x3_16_1024_1024_3_16_1_2_2_10_1024_Pipeline_Col_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln1073_reg_899 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i200_i_read_reg_858 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op66_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal icmp_ln1065_120_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1073_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mat_in_data323_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mat_blur_data324_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bottom_V_read_reg_876 : STD_LOGIC_VECTOR (1 downto 0);
    signal mid_V_read_reg_881 : STD_LOGIC_VECTOR (1 downto 0);
    signal tp_V_read_reg_886 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_V_reg_891 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_899_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln375_fu_454_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln375_reg_903 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln1065_120_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1065_120_reg_908_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal buf_V_load_reg_927 : STD_LOGIC_VECTOR (23 downto 0);
    signal buf_V_17_load_reg_934 : STD_LOGIC_VECTOR (23 downto 0);
    signal buf_V_18_load_reg_941 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter5_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter6_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter7_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter8_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter9_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_126_reg_948_pp0_iter10_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter5_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter6_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter7_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter8_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter9_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_128_reg_953_pp0_iter10_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter5_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter6_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter7_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter8_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter9_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_129_reg_958_pp0_iter10_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_s_fu_510_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_69_fu_515_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_70_fu_520_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_71_fu_525_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_72_fu_530_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_73_fu_535_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_74_fu_540_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_75_fu_545_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_76_fu_550_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal grp_xFapplygaussian3x3_16_s_fu_338_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call23 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call23 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call23 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call23 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call23 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call23 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call23 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call23 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call23 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call23 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call23 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call23 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call23 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp109 : BOOLEAN;
    signal grp_xFapplygaussian3x3_16_s_fu_353_D1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D6 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D7 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D8 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_D9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_353_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call33 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call33 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call33 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call33 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call33 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call33 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call33 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call33 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call33 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call33 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call33 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call33 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call33 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp119 : BOOLEAN;
    signal grp_xFapplygaussian3x3_16_s_fu_368_D1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D6 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D7 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D8 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_D9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFapplygaussian3x3_16_s_fu_368_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call43 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call43 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call43 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call43 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call43 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call43 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call43 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call43 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call43 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call43 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call43 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call43 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call43 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp129 : BOOLEAN;
    signal zext_ln587_120_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_fu_448_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln379_fu_462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_V_6_fu_108 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_11_fu_431_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_V : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_s_fu_112 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_122_fu_116 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_124_fu_120 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_121_fu_124 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_127_fu_486_p5 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_123_fu_128 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_1_fu_494_p5 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_125_fu_132 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_2_fu_502_p5 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1073_fu_421_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_1074 : BOOLEAN;
    signal ap_condition_1078 : BOOLEAN;
    signal ap_condition_1081 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component reversi_accel_xFapplygaussian3x3_16_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        D1 : IN STD_LOGIC_VECTOR (7 downto 0);
        D2 : IN STD_LOGIC_VECTOR (7 downto 0);
        D3 : IN STD_LOGIC_VECTOR (7 downto 0);
        D4 : IN STD_LOGIC_VECTOR (7 downto 0);
        D5 : IN STD_LOGIC_VECTOR (7 downto 0);
        D6 : IN STD_LOGIC_VECTOR (7 downto 0);
        D7 : IN STD_LOGIC_VECTOR (7 downto 0);
        D8 : IN STD_LOGIC_VECTOR (7 downto 0);
        D9 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component reversi_accel_mux_32_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component reversi_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    grp_xFapplygaussian3x3_16_s_fu_353 : component reversi_accel_xFapplygaussian3x3_16_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        D1 => grp_xFapplygaussian3x3_16_s_fu_353_D1,
        D2 => grp_xFapplygaussian3x3_16_s_fu_353_D2,
        D3 => grp_xFapplygaussian3x3_16_s_fu_353_D3,
        D4 => grp_xFapplygaussian3x3_16_s_fu_353_D4,
        D5 => grp_xFapplygaussian3x3_16_s_fu_353_D5,
        D6 => grp_xFapplygaussian3x3_16_s_fu_353_D6,
        D7 => grp_xFapplygaussian3x3_16_s_fu_353_D7,
        D8 => grp_xFapplygaussian3x3_16_s_fu_353_D8,
        D9 => grp_xFapplygaussian3x3_16_s_fu_353_D9,
        p_read1 => p_read,
        p_read2 => p_read1,
        ap_return => grp_xFapplygaussian3x3_16_s_fu_353_ap_return,
        ap_ce => grp_xFapplygaussian3x3_16_s_fu_353_ap_ce);

    grp_xFapplygaussian3x3_16_s_fu_368 : component reversi_accel_xFapplygaussian3x3_16_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        D1 => grp_xFapplygaussian3x3_16_s_fu_368_D1,
        D2 => grp_xFapplygaussian3x3_16_s_fu_368_D2,
        D3 => grp_xFapplygaussian3x3_16_s_fu_368_D3,
        D4 => grp_xFapplygaussian3x3_16_s_fu_368_D4,
        D5 => grp_xFapplygaussian3x3_16_s_fu_368_D5,
        D6 => grp_xFapplygaussian3x3_16_s_fu_368_D6,
        D7 => grp_xFapplygaussian3x3_16_s_fu_368_D7,
        D8 => grp_xFapplygaussian3x3_16_s_fu_368_D8,
        D9 => grp_xFapplygaussian3x3_16_s_fu_368_D9,
        p_read1 => p_read,
        p_read2 => p_read1,
        ap_return => grp_xFapplygaussian3x3_16_s_fu_368_ap_return,
        ap_ce => grp_xFapplygaussian3x3_16_s_fu_368_ap_ce);

    mux_32_24_1_1_U125 : component reversi_accel_mux_32_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        din2_WIDTH => 24,
        din3_WIDTH => 2,
        dout_WIDTH => 24)
    port map (
        din0 => buf_V_load_reg_927,
        din1 => buf_V_17_load_reg_934,
        din2 => buf_V_18_load_reg_941,
        din3 => tp_V,
        dout => p_Val2_127_fu_486_p5);

    mux_32_24_1_1_U126 : component reversi_accel_mux_32_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        din2_WIDTH => 24,
        din3_WIDTH => 2,
        dout_WIDTH => 24)
    port map (
        din0 => buf_V_load_reg_927,
        din1 => buf_V_17_load_reg_934,
        din2 => buf_V_18_load_reg_941,
        din3 => mid_V,
        dout => p_Val2_1_fu_494_p5);

    mux_32_24_1_1_U127 : component reversi_accel_mux_32_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        din2_WIDTH => 24,
        din3_WIDTH => 2,
        dout_WIDTH => 24)
    port map (
        din0 => buf_V_load_reg_927,
        din1 => buf_V_17_load_reg_934,
        din2 => buf_V_18_load_reg_941,
        din3 => bottom_V,
        dout => p_Val2_2_fu_502_p5);

    flow_control_loop_pipe_sequential_init_U : component reversi_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    col_V_6_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1073_fu_425_p2 = ap_const_lv1_1))) then 
                    col_V_6_fu_108 <= col_V_11_fu_431_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_V_6_fu_108 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_121_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_121_fu_124 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_121_fu_124 <= p_Val2_127_fu_486_p5;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_122_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_122_fu_116 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_122_fu_116 <= p_Val2_123_fu_128;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_123_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_123_fu_128 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_123_fu_128 <= p_Val2_1_fu_494_p5;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_124_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_124_fu_120 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_124_fu_120 <= p_Val2_125_fu_132;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_125_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_125_fu_132 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_125_fu_132 <= p_Val2_2_fu_502_p5;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_Val2_s_fu_112 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_1))) then 
                    p_Val2_s_fu_112 <= p_Val2_121_fu_124;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln1065_120_reg_908_pp0_iter10_reg <= icmp_ln1065_120_reg_908_pp0_iter9_reg;
                icmp_ln1065_120_reg_908_pp0_iter11_reg <= icmp_ln1065_120_reg_908_pp0_iter10_reg;
                icmp_ln1065_120_reg_908_pp0_iter2_reg <= icmp_ln1065_120_reg_908;
                icmp_ln1065_120_reg_908_pp0_iter3_reg <= icmp_ln1065_120_reg_908_pp0_iter2_reg;
                icmp_ln1065_120_reg_908_pp0_iter4_reg <= icmp_ln1065_120_reg_908_pp0_iter3_reg;
                icmp_ln1065_120_reg_908_pp0_iter5_reg <= icmp_ln1065_120_reg_908_pp0_iter4_reg;
                icmp_ln1065_120_reg_908_pp0_iter6_reg <= icmp_ln1065_120_reg_908_pp0_iter5_reg;
                icmp_ln1065_120_reg_908_pp0_iter7_reg <= icmp_ln1065_120_reg_908_pp0_iter6_reg;
                icmp_ln1065_120_reg_908_pp0_iter8_reg <= icmp_ln1065_120_reg_908_pp0_iter7_reg;
                icmp_ln1065_120_reg_908_pp0_iter9_reg <= icmp_ln1065_120_reg_908_pp0_iter8_reg;
                icmp_ln1073_reg_899_pp0_iter10_reg <= icmp_ln1073_reg_899_pp0_iter9_reg;
                icmp_ln1073_reg_899_pp0_iter2_reg <= icmp_ln1073_reg_899_pp0_iter1_reg;
                icmp_ln1073_reg_899_pp0_iter3_reg <= icmp_ln1073_reg_899_pp0_iter2_reg;
                icmp_ln1073_reg_899_pp0_iter4_reg <= icmp_ln1073_reg_899_pp0_iter3_reg;
                icmp_ln1073_reg_899_pp0_iter5_reg <= icmp_ln1073_reg_899_pp0_iter4_reg;
                icmp_ln1073_reg_899_pp0_iter6_reg <= icmp_ln1073_reg_899_pp0_iter5_reg;
                icmp_ln1073_reg_899_pp0_iter7_reg <= icmp_ln1073_reg_899_pp0_iter6_reg;
                icmp_ln1073_reg_899_pp0_iter8_reg <= icmp_ln1073_reg_899_pp0_iter7_reg;
                icmp_ln1073_reg_899_pp0_iter9_reg <= icmp_ln1073_reg_899_pp0_iter8_reg;
                p_Val2_126_reg_948_pp0_iter10_reg <= p_Val2_126_reg_948_pp0_iter9_reg;
                p_Val2_126_reg_948_pp0_iter5_reg <= p_Val2_126_reg_948;
                p_Val2_126_reg_948_pp0_iter6_reg <= p_Val2_126_reg_948_pp0_iter5_reg;
                p_Val2_126_reg_948_pp0_iter7_reg <= p_Val2_126_reg_948_pp0_iter6_reg;
                p_Val2_126_reg_948_pp0_iter8_reg <= p_Val2_126_reg_948_pp0_iter7_reg;
                p_Val2_126_reg_948_pp0_iter9_reg <= p_Val2_126_reg_948_pp0_iter8_reg;
                p_Val2_128_reg_953_pp0_iter10_reg <= p_Val2_128_reg_953_pp0_iter9_reg;
                p_Val2_128_reg_953_pp0_iter5_reg <= p_Val2_128_reg_953;
                p_Val2_128_reg_953_pp0_iter6_reg <= p_Val2_128_reg_953_pp0_iter5_reg;
                p_Val2_128_reg_953_pp0_iter7_reg <= p_Val2_128_reg_953_pp0_iter6_reg;
                p_Val2_128_reg_953_pp0_iter8_reg <= p_Val2_128_reg_953_pp0_iter7_reg;
                p_Val2_128_reg_953_pp0_iter9_reg <= p_Val2_128_reg_953_pp0_iter8_reg;
                p_Val2_129_reg_958_pp0_iter10_reg <= p_Val2_129_reg_958_pp0_iter9_reg;
                p_Val2_129_reg_958_pp0_iter5_reg <= p_Val2_129_reg_958;
                p_Val2_129_reg_958_pp0_iter6_reg <= p_Val2_129_reg_958_pp0_iter5_reg;
                p_Val2_129_reg_958_pp0_iter7_reg <= p_Val2_129_reg_958_pp0_iter6_reg;
                p_Val2_129_reg_958_pp0_iter8_reg <= p_Val2_129_reg_958_pp0_iter7_reg;
                p_Val2_129_reg_958_pp0_iter9_reg <= p_Val2_129_reg_958_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                col_V_reg_891 <= ap_sig_allocacmp_col_V;
                icmp_ln1073_reg_899 <= icmp_ln1073_fu_425_p2;
                icmp_ln1073_reg_899_pp0_iter1_reg <= icmp_ln1073_reg_899;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (((not((tp_V_read_reg_886 = ap_const_lv2_0)) and (icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (tp_V_read_reg_886 = ap_const_lv2_1)) or (not((mid_V_read_reg_881 = ap_const_lv2_0)) and (icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (mid_V_read_reg_881 = ap_const_lv2_1))) or ((icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1))))) then
                buf_V_17_load_reg_934 <= buf_V_17_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (((not((tp_V_read_reg_886 = ap_const_lv2_1)) and not((tp_V_read_reg_886 = ap_const_lv2_0)) and (icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (tp_V_read_reg_886 = ap_const_lv2_2)) or (not((mid_V_read_reg_881 = ap_const_lv2_1)) and not((mid_V_read_reg_881 = ap_const_lv2_0)) and (icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (mid_V_read_reg_881 = ap_const_lv2_2))) or ((icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_2))))) then
                buf_V_18_load_reg_941 <= buf_V_18_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and ((((icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (tp_V_read_reg_886 = ap_const_lv2_0)) or ((icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (mid_V_read_reg_881 = ap_const_lv2_0))) or ((icmp_ln1073_reg_899_pp0_iter2_reg = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0))))) then
                buf_V_load_reg_927 <= buf_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln1065_120_reg_908 <= icmp_ln1065_120_fu_457_p2;
                trunc_ln375_reg_903 <= trunc_ln375_fu_454_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Val2_126_reg_948 <= p_Val2_121_fu_124;
                p_Val2_128_reg_953 <= p_Val2_123_fu_128;
                p_Val2_129_reg_958 <= p_Val2_125_fu_132;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp109_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp109 <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp119_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp119 <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp129_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp129 <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter12, mat_in_data323_empty_n, ap_predicate_op66_read_state2, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((mat_blur_data324_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0)) or ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_pp0_stage0_iter12_assign_proc : process(mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_state13_pp0_stage0_iter12 <= ((mat_blur_data324_full_n = ap_const_logic_0) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0));
    end process;


    ap_block_state13_pp0_stage0_iter12_ignore_call23_assign_proc : process(mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_state13_pp0_stage0_iter12_ignore_call23 <= ((mat_blur_data324_full_n = ap_const_logic_0) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0));
    end process;


    ap_block_state13_pp0_stage0_iter12_ignore_call33_assign_proc : process(mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_state13_pp0_stage0_iter12_ignore_call33 <= ((mat_blur_data324_full_n = ap_const_logic_0) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0));
    end process;


    ap_block_state13_pp0_stage0_iter12_ignore_call43_assign_proc : process(mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg)
    begin
                ap_block_state13_pp0_stage0_iter12_ignore_call43 <= ((mat_blur_data324_full_n = ap_const_logic_0) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(mat_in_data323_empty_n, ap_predicate_op66_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_ignore_call23_assign_proc : process(mat_in_data323_empty_n, ap_predicate_op66_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_ignore_call23 <= ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_ignore_call33_assign_proc : process(mat_in_data323_empty_n, ap_predicate_op66_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_ignore_call33 <= ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_ignore_call43_assign_proc : process(mat_in_data323_empty_n, ap_predicate_op66_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_ignore_call43 <= ((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (mat_in_data323_empty_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call43 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_1074_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, ap_block_pp0_stage0, bottom_V_read_reg_876)
    begin
                ap_condition_1074 <= ((icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_1078_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, ap_block_pp0_stage0, bottom_V_read_reg_876)
    begin
                ap_condition_1078 <= (not((bottom_V_read_reg_876 = ap_const_lv2_1)) and not((bottom_V_read_reg_876 = ap_const_lv2_0)) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_1081_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, ap_block_pp0_stage0, bottom_V_read_reg_876)
    begin
                ap_condition_1081 <= ((icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1073_fu_425_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1073_fu_425_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln1073_reg_899_pp0_iter3_reg)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_899_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op66_read_state2_assign_proc : process(icmp_ln1073_reg_899, cmp_i_i200_i)
    begin
                ap_predicate_op66_read_state2 <= ((cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_V_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_V_6_fu_108, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_col_V <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_col_V <= col_V_6_fu_108;
        end if; 
    end process;

    bottom_V_read_reg_876 <= bottom_V;
    buf_V_17_address0 <= zext_ln379_fu_462_p1(10 - 1 downto 0);

    buf_V_17_address1_assign_proc : process(cmp_i_i200_i_read_reg_858, cmp_i_i200_i, zext_ln587_120_fu_442_p1, zext_ln587_fu_448_p1, ap_condition_1074)
    begin
        if ((ap_const_boolean_1 = ap_condition_1074)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_17_address1 <= zext_ln587_fu_448_p1(10 - 1 downto 0);
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_17_address1 <= zext_ln587_120_fu_442_p1(10 - 1 downto 0);
            else 
                buf_V_17_address1 <= "XXXXXXXXXX";
            end if;
        else 
            buf_V_17_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_17_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_V_17_ce0 <= ap_const_logic_1;
        else 
            buf_V_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_17_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if ((((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_17_ce1 <= ap_const_logic_1;
        else 
            buf_V_17_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_17_d1_assign_proc : process(mat_in_data323_dout, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_condition_1074)
    begin
        if ((ap_const_boolean_1 = ap_condition_1074)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_17_d1 <= mat_in_data323_dout;
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_17_d1 <= ap_const_lv24_0;
            else 
                buf_V_17_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            buf_V_17_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_17_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if ((((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_17_we1 <= ap_const_logic_1;
        else 
            buf_V_17_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_18_address0 <= zext_ln379_fu_462_p1(10 - 1 downto 0);

    buf_V_18_address1_assign_proc : process(cmp_i_i200_i_read_reg_858, cmp_i_i200_i, zext_ln587_120_fu_442_p1, zext_ln587_fu_448_p1, ap_condition_1078)
    begin
        if ((ap_const_boolean_1 = ap_condition_1078)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_18_address1 <= zext_ln587_fu_448_p1(10 - 1 downto 0);
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_18_address1 <= zext_ln587_120_fu_442_p1(10 - 1 downto 0);
            else 
                buf_V_18_address1 <= "XXXXXXXXXX";
            end if;
        else 
            buf_V_18_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_18_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_V_18_ce0 <= ap_const_logic_1;
        else 
            buf_V_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_18_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if (((not((bottom_V_read_reg_876 = ap_const_lv2_1)) and not((bottom_V_read_reg_876 = ap_const_lv2_0)) and (cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not((bottom_V_read_reg_876 = ap_const_lv2_1)) and not((bottom_V_read_reg_876 = ap_const_lv2_0)) and (cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_18_ce1 <= ap_const_logic_1;
        else 
            buf_V_18_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_18_d1_assign_proc : process(mat_in_data323_dout, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_condition_1078)
    begin
        if ((ap_const_boolean_1 = ap_condition_1078)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_18_d1 <= mat_in_data323_dout;
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_18_d1 <= ap_const_lv24_0;
            else 
                buf_V_18_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            buf_V_18_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_18_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if (((not((bottom_V_read_reg_876 = ap_const_lv2_1)) and not((bottom_V_read_reg_876 = ap_const_lv2_0)) and (cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not((bottom_V_read_reg_876 = ap_const_lv2_1)) and not((bottom_V_read_reg_876 = ap_const_lv2_0)) and (cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_18_we1 <= ap_const_logic_1;
        else 
            buf_V_18_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_address0 <= zext_ln379_fu_462_p1(10 - 1 downto 0);

    buf_V_address1_assign_proc : process(cmp_i_i200_i_read_reg_858, cmp_i_i200_i, zext_ln587_120_fu_442_p1, zext_ln587_fu_448_p1, ap_condition_1081)
    begin
        if ((ap_const_boolean_1 = ap_condition_1081)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_address1 <= zext_ln587_fu_448_p1(10 - 1 downto 0);
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_address1 <= zext_ln587_120_fu_442_p1(10 - 1 downto 0);
            else 
                buf_V_address1 <= "XXXXXXXXXX";
            end if;
        else 
            buf_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if ((((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_ce1 <= ap_const_logic_1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d1_assign_proc : process(mat_in_data323_dout, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_condition_1081)
    begin
        if ((ap_const_boolean_1 = ap_condition_1081)) then
            if ((cmp_i_i200_i = ap_const_lv1_1)) then 
                buf_V_d1 <= mat_in_data323_dout;
            elsif ((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0)) then 
                buf_V_d1 <= ap_const_lv24_0;
            else 
                buf_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            buf_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_899, cmp_i_i200_i_read_reg_858, cmp_i_i200_i, ap_block_pp0_stage0_11001, bottom_V_read_reg_876)
    begin
        if ((((cmp_i_i200_i_read_reg_858 = ap_const_lv1_0) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((cmp_i_i200_i = ap_const_lv1_1) and (icmp_ln1073_reg_899 = ap_const_lv1_1) and (bottom_V_read_reg_876 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_V_we1 <= ap_const_logic_1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i200_i_read_reg_858 <= cmp_i_i200_i;
    col_V_11_fu_431_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_V) + unsigned(ap_const_lv13_1));

    grp_xFapplygaussian3x3_16_s_fu_338_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp109)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp109))) then 
            grp_xFapplygaussian3x3_16_s_fu_338_ap_ce <= ap_const_logic_1;
        else 
            grp_xFapplygaussian3x3_16_s_fu_338_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFapplygaussian3x3_16_s_fu_353_D1 <= p_Val2_s_fu_112(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D2 <= p_Val2_121_fu_124(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D3 <= p_Val2_127_fu_486_p5(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D4 <= p_Val2_122_fu_116(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D5 <= p_Val2_123_fu_128(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D6 <= p_Val2_1_fu_494_p5(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D7 <= p_Val2_124_fu_120(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D8 <= p_Val2_125_fu_132(15 downto 8);
    grp_xFapplygaussian3x3_16_s_fu_353_D9 <= p_Val2_2_fu_502_p5(15 downto 8);

    grp_xFapplygaussian3x3_16_s_fu_353_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp119)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp119))) then 
            grp_xFapplygaussian3x3_16_s_fu_353_ap_ce <= ap_const_logic_1;
        else 
            grp_xFapplygaussian3x3_16_s_fu_353_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFapplygaussian3x3_16_s_fu_368_D1 <= p_Val2_s_fu_112(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D2 <= p_Val2_121_fu_124(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D3 <= p_Val2_127_fu_486_p5(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D4 <= p_Val2_122_fu_116(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D5 <= p_Val2_123_fu_128(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D6 <= p_Val2_1_fu_494_p5(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D7 <= p_Val2_124_fu_120(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D8 <= p_Val2_125_fu_132(23 downto 16);
    grp_xFapplygaussian3x3_16_s_fu_368_D9 <= p_Val2_2_fu_502_p5(23 downto 16);

    grp_xFapplygaussian3x3_16_s_fu_368_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp129)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp129))) then 
            grp_xFapplygaussian3x3_16_s_fu_368_ap_ce <= ap_const_logic_1;
        else 
            grp_xFapplygaussian3x3_16_s_fu_368_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFapplygaussian3x3_16_s_fu_560_p_ce <= grp_xFapplygaussian3x3_16_s_fu_338_ap_ce;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din1 <= p_Result_s_fu_510_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din10 <= p_read;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din11 <= p_read1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din2 <= p_Result_69_fu_515_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din3 <= p_Result_70_fu_520_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din4 <= p_Result_71_fu_525_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din5 <= p_Result_72_fu_530_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din6 <= p_Result_73_fu_535_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din7 <= p_Result_74_fu_540_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din8 <= p_Result_75_fu_545_p1;
    grp_xFapplygaussian3x3_16_s_fu_560_p_din9 <= p_Result_76_fu_550_p1;
    icmp_ln1065_120_fu_457_p2 <= "1" when (col_V_reg_891 = ap_const_lv13_0) else "0";
    icmp_ln1073_fu_425_p2 <= "1" when (unsigned(zext_ln1073_fu_421_p1) < unsigned(img_width)) else "0";

    mat_blur_data324_blk_n_assign_proc : process(ap_enable_reg_pp0_iter12, mat_blur_data324_full_n, icmp_ln1065_120_reg_908_pp0_iter11_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0))) then 
            mat_blur_data324_blk_n <= mat_blur_data324_full_n;
        else 
            mat_blur_data324_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mat_blur_data324_din <= ((grp_xFapplygaussian3x3_16_s_fu_368_ap_return & grp_xFapplygaussian3x3_16_s_fu_353_ap_return) & grp_xFapplygaussian3x3_16_s_fu_560_p_dout0);

    mat_blur_data324_write_assign_proc : process(ap_enable_reg_pp0_iter12, icmp_ln1065_120_reg_908_pp0_iter11_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1065_120_reg_908_pp0_iter11_reg = ap_const_lv1_0))) then 
            mat_blur_data324_write <= ap_const_logic_1;
        else 
            mat_blur_data324_write <= ap_const_logic_0;
        end if; 
    end process;


    mat_in_data323_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mat_in_data323_empty_n, ap_predicate_op66_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            mat_in_data323_blk_n <= mat_in_data323_empty_n;
        else 
            mat_in_data323_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mat_in_data323_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op66_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op66_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            mat_in_data323_read <= ap_const_logic_1;
        else 
            mat_in_data323_read <= ap_const_logic_0;
        end if; 
    end process;

    mid_V_read_reg_881 <= mid_V;
    p_Result_69_fu_515_p1 <= p_Val2_121_fu_124(8 - 1 downto 0);
    p_Result_70_fu_520_p1 <= p_Val2_127_fu_486_p5(8 - 1 downto 0);
    p_Result_71_fu_525_p1 <= p_Val2_122_fu_116(8 - 1 downto 0);
    p_Result_72_fu_530_p1 <= p_Val2_123_fu_128(8 - 1 downto 0);
    p_Result_73_fu_535_p1 <= p_Val2_1_fu_494_p5(8 - 1 downto 0);
    p_Result_74_fu_540_p1 <= p_Val2_124_fu_120(8 - 1 downto 0);
    p_Result_75_fu_545_p1 <= p_Val2_125_fu_132(8 - 1 downto 0);
    p_Result_76_fu_550_p1 <= p_Val2_2_fu_502_p5(8 - 1 downto 0);
    p_Result_s_fu_510_p1 <= p_Val2_s_fu_112(8 - 1 downto 0);
    p_Val2_121_out <= p_Val2_126_reg_948_pp0_iter10_reg;

    p_Val2_121_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_121_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_121_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_122_out <= p_Val2_122_fu_116;

    p_Val2_122_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_122_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_122_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_123_out <= p_Val2_128_reg_953_pp0_iter10_reg;

    p_Val2_123_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_123_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_123_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_124_out <= p_Val2_124_fu_120;

    p_Val2_124_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_124_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_124_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_125_out <= p_Val2_129_reg_958_pp0_iter10_reg;

    p_Val2_125_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_125_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_125_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_out <= p_Val2_s_fu_112;

    p_Val2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1073_reg_899_pp0_iter10_reg)
    begin
        if (((icmp_ln1073_reg_899_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_Val2_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tp_V_read_reg_886 <= tp_V;
    trunc_ln375_fu_454_p1 <= col_V_reg_891(10 - 1 downto 0);
    zext_ln1073_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V),16));
    zext_ln379_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln375_reg_903),64));
    zext_ln587_120_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_891),64));
    zext_ln587_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_891),64));
end behav;
