-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reversi_accel_xferode_1024_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_ero2_data334_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    mat_ero2_data334_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_ero2_data334_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_ero2_data334_empty_n : IN STD_LOGIC;
    mat_ero2_data334_read : OUT STD_LOGIC;
    mat_lap2_data336_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    mat_lap2_data336_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_lap2_data336_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    mat_lap2_data336_full_n : IN STD_LOGIC;
    mat_lap2_data336_write : OUT STD_LOGIC;
    add_ln1834 : IN STD_LOGIC_VECTOR (13 downto 0);
    buf_V_8_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_8_ce0 : OUT STD_LOGIC;
    buf_V_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_8_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_8_ce1 : OUT STD_LOGIC;
    buf_V_8_we1 : OUT STD_LOGIC;
    buf_V_8_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_ce1 : OUT STD_LOGIC;
    buf_V_we1 : OUT STD_LOGIC;
    buf_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_7_ce0 : OUT STD_LOGIC;
    buf_V_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_V_7_ce1 : OUT STD_LOGIC;
    buf_V_7_we1 : OUT STD_LOGIC;
    buf_V_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_width : IN STD_LOGIC_VECTOR (15 downto 0);
    empty_54 : IN STD_LOGIC_VECTOR (12 downto 0);
    empty_55 : IN STD_LOGIC_VECTOR (12 downto 0);
    empty : IN STD_LOGIC_VECTOR (12 downto 0);
    p_cast : IN STD_LOGIC_VECTOR (1 downto 0);
    cmp_i_i142_i : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of reversi_accel_xferode_1024_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln1073_reg_520 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_51_reg_524 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i142_i_read_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op60_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal icmp_ln1077_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1077_reg_543_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1073_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mat_ero2_data334_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mat_lap2_data336_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_cast_read_reg_495 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_V_3_reg_514 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1073_reg_520_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_520_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_reg_520_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_51_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_51_reg_524_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_51_reg_524_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal buf_V_8_addr_reg_528 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_addr_reg_533 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_7_addr_reg_538 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln1077_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1077_reg_543_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1077_reg_543_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1077_reg_543_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal buf_cop_V_fu_341_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_V_8_fu_352_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_V_9_fu_363_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_62_load_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_temp_copy_extract_V_0_15_reg_568 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_140_fu_406_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_140_reg_574 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_143_fu_449_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_143_reg_580 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253_ap_ready : STD_LOGIC;
    signal src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_ready : STD_LOGIC;
    signal src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265_ap_ready : STD_LOGIC;
    signal src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_buf_cop_V_15_0_reg_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_buf_cop_V_15_0_reg_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_buf_cop_V_15_0_reg_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_buf_cop_V_15_0_reg_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_buf_cop_V_15_0_reg_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_buf_cop_V_10_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_buf_cop_V_10_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_buf_cop_V_10_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_buf_cop_V_10_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_buf_cop_V_10_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv_i99_i_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_V_fu_88 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_4_fu_313_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_V_3 : STD_LOGIC_VECTOR (12 downto 0);
    signal max_V_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_62_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_63_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1073_3_fu_303_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln1073_fu_299_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1073_52_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_139_fu_392_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1073_53_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1073_54_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_141_fu_438_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1073_55_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_273 : BOOLEAN;
    signal ap_condition_501 : BOOLEAN;
    signal ap_condition_505 : BOOLEAN;
    signal ap_condition_508 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component reversi_accel_xfExtractPixels_1_1_0_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reversi_accel_mux_313_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reversi_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253 : component reversi_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253_ap_ready,
        p_read1 => ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_231,
        ap_return => src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253_ap_return);

    src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259 : component reversi_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_ready,
        p_read1 => ap_phi_reg_pp0_iter4_buf_cop_V_15_0_reg_220,
        ap_return => src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_return);

    src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265 : component reversi_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265_ap_ready,
        p_read1 => ap_phi_reg_pp0_iter4_buf_cop_V_10_reg_242,
        ap_return => src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265_ap_return);

    mux_313_8_1_1_U400 : component reversi_accel_mux_313_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 13,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_7_q0,
        din2 => buf_V_8_q0,
        din3 => empty_54,
        dout => buf_cop_V_fu_341_p5);

    mux_313_8_1_1_U401 : component reversi_accel_mux_313_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 13,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_7_q0,
        din2 => buf_V_8_q0,
        din3 => empty_55,
        dout => buf_cop_V_8_fu_352_p5);

    mux_313_8_1_1_U402 : component reversi_accel_mux_313_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 13,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_7_q0,
        din2 => buf_V_8_q0,
        din3 => empty,
        dout => buf_cop_V_9_fu_363_p5);

    flow_control_loop_pipe_sequential_init_U : component reversi_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_273)) then
                if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_1) and (icmp_ln1073_51_fu_319_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_231 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_231 <= ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_231;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_buf_cop_V_10_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_273)) then
                if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_1) and (icmp_ln1073_51_fu_319_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_10_reg_242 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_10_reg_242 <= ap_phi_reg_pp0_iter0_buf_cop_V_10_reg_242;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_buf_cop_V_15_0_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_273)) then
                if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_1) and (icmp_ln1073_51_fu_319_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_15_0_reg_220 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_buf_cop_V_15_0_reg_220 <= ap_phi_reg_pp0_iter0_buf_cop_V_15_0_reg_220;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if (((icmp_ln1073_51_reg_524_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln1073_reg_520_pp0_iter2_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_231 <= buf_cop_V_fu_341_p5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_231 <= ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_231;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_buf_cop_V_10_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if (((icmp_ln1073_51_reg_524_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln1073_reg_520_pp0_iter2_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_10_reg_242 <= buf_cop_V_9_fu_363_p5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_10_reg_242 <= ap_phi_reg_pp0_iter3_buf_cop_V_10_reg_242;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_buf_cop_V_15_0_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if (((icmp_ln1073_51_reg_524_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln1073_reg_520_pp0_iter2_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_15_0_reg_220 <= buf_cop_V_8_fu_352_p5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_buf_cop_V_15_0_reg_220 <= ap_phi_reg_pp0_iter3_buf_cop_V_15_0_reg_220;
                end if;
            end if; 
        end if;
    end process;

    col_V_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    col_V_fu_88 <= col_V_4_fu_313_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_V_fu_88 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    max_V_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    max_V_fu_92 <= ap_const_lv8_FF;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_1))) then 
                    max_V_fu_92 <= src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_253_ap_return;
                end if;
            end if; 
        end if;
    end process;

    ret_62_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ret_62_fu_100 <= ap_const_lv8_FF;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_1))) then 
                    ret_62_fu_100 <= src_buf_temp_copy_extract_V_0_16_xfExtractPixels_1_1_0_s_fu_265_ap_return;
                end if;
            end if; 
        end if;
    end process;

    ret_63_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ret_63_fu_104 <= ap_const_lv8_FF;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_1))) then 
                    ret_63_fu_104 <= src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_return;
                end if;
            end if; 
        end if;
    end process;

    ret_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ret_fu_96 <= ap_const_lv8_FF;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_1))) then 
                    ret_fu_96 <= ret_63_fu_104;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                col_V_3_reg_514 <= ap_sig_allocacmp_col_V_3;
                icmp_ln1073_51_reg_524_pp0_iter1_reg <= icmp_ln1073_51_reg_524;
                icmp_ln1073_reg_520 <= icmp_ln1073_fu_307_p2;
                icmp_ln1073_reg_520_pp0_iter1_reg <= icmp_ln1073_reg_520;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                icmp_ln1073_51_reg_524_pp0_iter2_reg <= icmp_ln1073_51_reg_524_pp0_iter1_reg;
                icmp_ln1073_reg_520_pp0_iter2_reg <= icmp_ln1073_reg_520_pp0_iter1_reg;
                icmp_ln1073_reg_520_pp0_iter3_reg <= icmp_ln1073_reg_520_pp0_iter2_reg;
                icmp_ln1077_reg_543_pp0_iter2_reg <= icmp_ln1077_reg_543;
                icmp_ln1077_reg_543_pp0_iter3_reg <= icmp_ln1077_reg_543_pp0_iter2_reg;
                icmp_ln1077_reg_543_pp0_iter4_reg <= icmp_ln1077_reg_543_pp0_iter3_reg;
                icmp_ln1077_reg_543_pp0_iter5_reg <= icmp_ln1077_reg_543_pp0_iter4_reg;
                max_V_143_reg_580 <= max_V_143_fu_449_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_231 <= ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_231;
                ap_phi_reg_pp0_iter2_buf_cop_V_10_reg_242 <= ap_phi_reg_pp0_iter1_buf_cop_V_10_reg_242;
                ap_phi_reg_pp0_iter2_buf_cop_V_15_0_reg_220 <= ap_phi_reg_pp0_iter1_buf_cop_V_15_0_reg_220;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_231 <= ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_231;
                ap_phi_reg_pp0_iter3_buf_cop_V_10_reg_242 <= ap_phi_reg_pp0_iter2_buf_cop_V_10_reg_242;
                ap_phi_reg_pp0_iter3_buf_cop_V_15_0_reg_220 <= ap_phi_reg_pp0_iter2_buf_cop_V_15_0_reg_220;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buf_V_7_addr_reg_538 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);
                buf_V_8_addr_reg_528 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);
                buf_V_addr_reg_533 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1073_51_reg_524 <= icmp_ln1073_51_fu_319_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1077_reg_543 <= icmp_ln1077_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_1))) then
                max_V_140_reg_574 <= max_V_140_fu_406_p3;
                ret_62_load_reg_562 <= ret_62_fu_100;
                src_buf_temp_copy_extract_V_0_15_reg_568 <= src_buf_temp_copy_extract_V_0_15_xfExtractPixels_1_1_0_s_fu_259_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, mat_ero2_data334_empty_n, ap_predicate_op60_read_state2, mat_lap2_data336_full_n, icmp_ln1077_reg_543_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (mat_lap2_data336_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_predicate_op60_read_state2 = ap_const_boolean_1) and (mat_ero2_data334_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, mat_ero2_data334_empty_n, ap_predicate_op60_read_state2, mat_lap2_data336_full_n, icmp_ln1077_reg_543_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (mat_lap2_data336_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_predicate_op60_read_state2 = ap_const_boolean_1) and (mat_ero2_data334_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, mat_ero2_data334_empty_n, ap_predicate_op60_read_state2, mat_lap2_data336_full_n, icmp_ln1077_reg_543_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (mat_lap2_data336_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_predicate_op60_read_state2 = ap_const_boolean_1) and (mat_ero2_data334_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(mat_ero2_data334_empty_n, ap_predicate_op60_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op60_read_state2 = ap_const_boolean_1) and (mat_ero2_data334_empty_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter6_assign_proc : process(mat_lap2_data336_full_n, icmp_ln1077_reg_543_pp0_iter5_reg)
    begin
                ap_block_state7_pp0_stage0_iter6 <= ((icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (mat_lap2_data336_full_n = ap_const_logic_0));
    end process;


    ap_condition_273_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_273 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_501_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, ap_block_pp0_stage0, p_cast_read_reg_495)
    begin
                ap_condition_501 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_1));
    end process;


    ap_condition_505_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, ap_block_pp0_stage0, p_cast_read_reg_495)
    begin
                ap_condition_505 <= (not((p_cast_read_reg_495 = ap_const_lv2_0)) and not((p_cast_read_reg_495 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_508_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, ap_block_pp0_stage0, p_cast_read_reg_495)
    begin
                ap_condition_508 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1073_fu_307_p2)
    begin
        if (((icmp_ln1073_fu_307_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln1073_reg_520_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln1073_reg_520_pp0_iter3_reg = ap_const_lv1_0))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_231 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_buf_cop_V_10_reg_242 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_buf_cop_V_15_0_reg_220 <= "XXXXXXXX";

    ap_predicate_op60_read_state2_assign_proc : process(icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i)
    begin
                ap_predicate_op60_read_state2 <= ((cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_V_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_V_fu_88, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_V_3 <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_col_V_3 <= col_V_fu_88;
        end if; 
    end process;

    buf_V_7_address0 <= buf_V_7_addr_reg_538;
    buf_V_7_address1 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);

    buf_V_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_V_7_ce0 <= ap_const_logic_1;
        else 
            buf_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_1)))) then 
            buf_V_7_ce1 <= ap_const_logic_1;
        else 
            buf_V_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_7_d1_assign_proc : process(mat_ero2_data334_dout, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_condition_501)
    begin
        if ((ap_const_boolean_1 = ap_condition_501)) then
            if ((cmp_i_i142_i = ap_const_lv1_1)) then 
                buf_V_7_d1 <= mat_ero2_data334_dout;
            elsif ((cmp_i_i142_i_read_reg_491 = ap_const_lv1_0)) then 
                buf_V_7_d1 <= ap_const_lv8_FF;
            else 
                buf_V_7_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_7_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_7_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_1)))) then 
            buf_V_7_we1 <= ap_const_logic_1;
        else 
            buf_V_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_8_address0 <= buf_V_8_addr_reg_528;
    buf_V_8_address1 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);

    buf_V_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_V_8_ce0 <= ap_const_logic_1;
        else 
            buf_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if (((not((p_cast_read_reg_495 = ap_const_lv2_0)) and not((p_cast_read_reg_495 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or (not((p_cast_read_reg_495 = ap_const_lv2_0)) and not((p_cast_read_reg_495 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buf_V_8_ce1 <= ap_const_logic_1;
        else 
            buf_V_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_8_d1_assign_proc : process(mat_ero2_data334_dout, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_condition_505)
    begin
        if ((ap_const_boolean_1 = ap_condition_505)) then
            if ((cmp_i_i142_i = ap_const_lv1_1)) then 
                buf_V_8_d1 <= mat_ero2_data334_dout;
            elsif ((cmp_i_i142_i_read_reg_491 = ap_const_lv1_0)) then 
                buf_V_8_d1 <= ap_const_lv8_FF;
            else 
                buf_V_8_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_8_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_8_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if (((not((p_cast_read_reg_495 = ap_const_lv2_0)) and not((p_cast_read_reg_495 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or (not((p_cast_read_reg_495 = ap_const_lv2_0)) and not((p_cast_read_reg_495 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buf_V_8_we1 <= ap_const_logic_1;
        else 
            buf_V_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_address0 <= buf_V_addr_reg_533;
    buf_V_address1 <= conv_i99_i_fu_330_p1(10 - 1 downto 0);

    buf_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_0)))) then 
            buf_V_ce1 <= ap_const_logic_1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d1_assign_proc : process(mat_ero2_data334_dout, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_condition_508)
    begin
        if ((ap_const_boolean_1 = ap_condition_508)) then
            if ((cmp_i_i142_i = ap_const_lv1_1)) then 
                buf_V_d1 <= mat_ero2_data334_dout;
            elsif ((cmp_i_i142_i_read_reg_491 = ap_const_lv1_0)) then 
                buf_V_d1 <= ap_const_lv8_FF;
            else 
                buf_V_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1073_reg_520, icmp_ln1073_51_reg_524, cmp_i_i142_i_read_reg_491, cmp_i_i142_i, ap_block_pp0_stage0_11001, p_cast_read_reg_495)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i = ap_const_lv1_1) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i142_i_read_reg_491 = ap_const_lv1_0) and (icmp_ln1073_51_reg_524 = ap_const_lv1_1) and (icmp_ln1073_reg_520 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_cast_read_reg_495 = ap_const_lv2_0)))) then 
            buf_V_we1 <= ap_const_logic_1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i142_i_read_reg_491 <= cmp_i_i142_i;
    col_V_4_fu_313_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_V_3) + unsigned(ap_const_lv13_1));
    conv_i99_i_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_3_reg_514),64));
    icmp_ln1073_51_fu_319_p2 <= "1" when (unsigned(zext_ln1073_fu_299_p1) < unsigned(img_width)) else "0";
    icmp_ln1073_52_fu_386_p2 <= "1" when (unsigned(max_V_fu_92) > unsigned(ret_fu_96)) else "0";
    icmp_ln1073_53_fu_400_p2 <= "1" when (unsigned(max_V_139_fu_392_p3) > unsigned(ret_63_fu_104)) else "0";
    icmp_ln1073_54_fu_434_p2 <= "1" when (unsigned(max_V_140_reg_574) > unsigned(src_buf_temp_copy_extract_V_0_15_reg_568)) else "0";
    icmp_ln1073_55_fu_444_p2 <= "1" when (unsigned(max_V_141_fu_438_p3) > unsigned(ret_62_load_reg_562)) else "0";
    icmp_ln1073_fu_307_p2 <= "1" when (unsigned(zext_ln1073_3_fu_303_p1) < unsigned(add_ln1834)) else "0";
    icmp_ln1077_fu_336_p2 <= "1" when (col_V_3_reg_514 = ap_const_lv13_0) else "0";

    mat_ero2_data334_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mat_ero2_data334_empty_n, ap_predicate_op60_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op60_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mat_ero2_data334_blk_n <= mat_ero2_data334_empty_n;
        else 
            mat_ero2_data334_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mat_ero2_data334_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op60_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op60_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mat_ero2_data334_read <= ap_const_logic_1;
        else 
            mat_ero2_data334_read <= ap_const_logic_0;
        end if; 
    end process;


    mat_lap2_data336_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, mat_lap2_data336_full_n, icmp_ln1077_reg_543_pp0_iter5_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            mat_lap2_data336_blk_n <= mat_lap2_data336_full_n;
        else 
            mat_lap2_data336_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mat_lap2_data336_din <= max_V_143_reg_580;

    mat_lap2_data336_write_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln1077_reg_543_pp0_iter5_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1077_reg_543_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            mat_lap2_data336_write <= ap_const_logic_1;
        else 
            mat_lap2_data336_write <= ap_const_logic_0;
        end if; 
    end process;

    max_V_139_fu_392_p3 <= 
        ret_fu_96 when (icmp_ln1073_52_fu_386_p2(0) = '1') else 
        max_V_fu_92;
    max_V_140_fu_406_p3 <= 
        ret_63_fu_104 when (icmp_ln1073_53_fu_400_p2(0) = '1') else 
        max_V_139_fu_392_p3;
    max_V_141_fu_438_p3 <= 
        src_buf_temp_copy_extract_V_0_15_reg_568 when (icmp_ln1073_54_fu_434_p2(0) = '1') else 
        max_V_140_reg_574;
    max_V_143_fu_449_p3 <= 
        ret_62_load_reg_562 when (icmp_ln1073_55_fu_444_p2(0) = '1') else 
        max_V_141_fu_438_p3;
    p_cast_read_reg_495 <= p_cast;
    zext_ln1073_3_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V_3),14));
    zext_ln1073_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V_3),16));
end behav;
