// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reversi_accel_dilate_0_0_1024_1024_0_7_7_1_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        mat_green_4235_dout,
        mat_green_4235_empty_n,
        mat_green_4235_read,
        mat_dil_a_4236_din,
        mat_dil_a_4236_full_n,
        mat_dil_a_4236_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [7:0] mat_green_4235_dout;
input   mat_green_4235_empty_n;
output   mat_green_4235_read;
output  [7:0] mat_dil_a_4236_din;
input   mat_dil_a_4236_full_n;
output   mat_dil_a_4236_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mat_green_4235_read;
reg mat_dil_a_4236_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] imgheight_fu_42_p1;
reg   [15:0] imgheight_reg_52;
wire   [15:0] imgwidth_fu_47_p1;
reg   [15:0] imgwidth_reg_57;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_idle;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_ready;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_green_4235_read;
wire   [7:0] grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_din;
wire    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_write;
reg    grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg;
reg    ap_block_state1_ignore_call6;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg = 1'b0;
end

reversi_accel_xfdilate_1024_1024_1_0_1_0_1027_7_7_s grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start),
    .ap_done(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done),
    .ap_idle(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_idle),
    .ap_ready(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_ready),
    .mat_green_4235_dout(mat_green_4235_dout),
    .mat_green_4235_empty_n(mat_green_4235_empty_n),
    .mat_green_4235_read(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_green_4235_read),
    .mat_dil_a_4236_din(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_din),
    .mat_dil_a_4236_full_n(mat_dil_a_4236_full_n),
    .mat_dil_a_4236_write(grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_write),
    .img_height(imgheight_reg_52),
    .img_width(imgwidth_reg_57)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_ready == 1'b1)) begin
            grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        imgheight_reg_52 <= imgheight_fu_42_p1;
        imgwidth_reg_57 <= imgwidth_fu_47_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_dil_a_4236_write = grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_write;
    end else begin
        mat_dil_a_4236_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_green_4235_read = grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_green_4235_read;
    end else begin
        mat_green_4235_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call6 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start = grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_ap_start_reg;

assign imgheight_fu_42_p1 = p_read[15:0];

assign imgwidth_fu_47_p1 = p_read1[15:0];

assign mat_dil_a_4236_din = grp_xfdilate_1024_1024_1_0_1_0_1027_7_7_s_fu_32_mat_dil_a_4236_din;

endmodule //reversi_accel_dilate_0_0_1024_1024_0_7_7_1_1_s
