// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reversi_accel_xfdilate_1024_1024_1_0_1_0_1025_3_3_Pipeline_Col_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_lap_4242_dout,
        mat_lap_4242_empty_n,
        mat_lap_4242_read,
        mat_dil_b_4243_din,
        mat_dil_b_4243_full_n,
        mat_dil_b_4243_write,
        add_ln1795,
        p_read,
        p_read2,
        p_read6,
        p_read8,
        img_width,
        buf_V_0_address0,
        buf_V_0_ce0,
        buf_V_0_q0,
        buf_V_0_address1,
        buf_V_0_ce1,
        buf_V_0_we1,
        buf_V_0_d1,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_q0,
        buf_V_1_address1,
        buf_V_1_ce1,
        buf_V_1_we1,
        buf_V_1_d1,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_q0,
        buf_V_2_address1,
        buf_V_2_ce1,
        buf_V_2_we1,
        buf_V_2_d1,
        trunc_ln4,
        trunc_ln136_6,
        trunc_ln,
        cmp_i_i115_i
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] mat_lap_4242_dout;
input   mat_lap_4242_empty_n;
output   mat_lap_4242_read;
output  [7:0] mat_dil_b_4243_din;
input   mat_dil_b_4243_full_n;
output   mat_dil_b_4243_write;
input  [13:0] add_ln1795;
input  [0:0] p_read;
input  [0:0] p_read2;
input  [0:0] p_read6;
input  [0:0] p_read8;
input  [15:0] img_width;
output  [9:0] buf_V_0_address0;
output   buf_V_0_ce0;
input  [7:0] buf_V_0_q0;
output  [9:0] buf_V_0_address1;
output   buf_V_0_ce1;
output   buf_V_0_we1;
output  [7:0] buf_V_0_d1;
output  [9:0] buf_V_1_address0;
output   buf_V_1_ce0;
input  [7:0] buf_V_1_q0;
output  [9:0] buf_V_1_address1;
output   buf_V_1_ce1;
output   buf_V_1_we1;
output  [7:0] buf_V_1_d1;
output  [9:0] buf_V_2_address0;
output   buf_V_2_ce0;
input  [7:0] buf_V_2_q0;
output  [9:0] buf_V_2_address1;
output   buf_V_2_ce1;
output   buf_V_2_we1;
output  [7:0] buf_V_2_d1;
input  [1:0] trunc_ln4;
input  [1:0] trunc_ln136_6;
input  [1:0] trunc_ln;
input  [0:0] cmp_i_i115_i;

reg ap_idle;
reg mat_lap_4242_read;
reg mat_dil_b_4243_write;
reg buf_V_0_ce0;
reg[9:0] buf_V_0_address1;
reg buf_V_0_ce1;
reg buf_V_0_we1;
reg[7:0] buf_V_0_d1;
reg buf_V_1_ce0;
reg[9:0] buf_V_1_address1;
reg buf_V_1_ce1;
reg buf_V_1_we1;
reg[7:0] buf_V_1_d1;
reg buf_V_2_ce0;
reg[9:0] buf_V_2_address1;
reg buf_V_2_ce1;
reg buf_V_2_we1;
reg[7:0] buf_V_2_d1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln1057_reg_749;
reg   [0:0] icmp_ln1057_62_reg_753;
wire   [0:0] cmp_i_i115_i_read_reg_703;
reg    ap_predicate_op67_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg   [0:0] icmp_ln1061_reg_777;
reg   [0:0] icmp_ln1061_reg_777_pp0_iter6_reg;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1057_fu_408_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mat_dil_b_4243_blk_n;
wire    ap_block_pp0_stage0;
reg    mat_lap_4242_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] cmp_i_i115_i_read_read_fu_120_p2;
wire   [1:0] trunc_ln_read_reg_707;
wire   [0:0] p_read_1_reg_721;
wire   [0:0] p_read_2_reg_726;
wire   [0:0] p_read_3_reg_731;
reg   [12:0] col_V_7_reg_741;
reg   [12:0] col_V_7_reg_741_pp0_iter1_reg;
reg   [0:0] icmp_ln1057_reg_749_pp0_iter1_reg;
reg   [0:0] icmp_ln1057_reg_749_pp0_iter2_reg;
reg   [0:0] icmp_ln1057_reg_749_pp0_iter3_reg;
reg   [0:0] icmp_ln1057_reg_749_pp0_iter4_reg;
reg   [0:0] icmp_ln1057_reg_749_pp0_iter5_reg;
wire   [0:0] icmp_ln1057_62_fu_420_p2;
reg   [0:0] icmp_ln1057_62_reg_753_pp0_iter1_reg;
reg   [0:0] icmp_ln1057_62_reg_753_pp0_iter2_reg;
wire   [0:0] icmp_ln1061_fu_449_p2;
reg   [0:0] icmp_ln1061_reg_777_pp0_iter3_reg;
reg   [0:0] icmp_ln1061_reg_777_pp0_iter4_reg;
reg   [0:0] icmp_ln1061_reg_777_pp0_iter5_reg;
wire   [7:0] buf_cop_V_0_fu_454_p5;
wire   [7:0] tmp_fu_465_p5;
wire   [7:0] src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350_ap_return;
reg   [7:0] src_buf_V_2_1_reg_791;
reg   [7:0] src_buf_V_2_1_reg_791_pp0_iter5_reg;
reg   [7:0] src_buf_V_2_1_reg_791_pp0_iter6_reg;
wire   [7:0] max_V_243_fu_517_p3;
reg   [7:0] max_V_243_reg_798;
wire   [7:0] src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_return;
reg   [7:0] src_buf_V_1_1_reg_804;
wire   [7:0] max_V_245_fu_558_p3;
reg   [7:0] max_V_245_reg_809;
wire   [0:0] icmp_ln1065_51_fu_566_p2;
reg   [0:0] icmp_ln1065_51_reg_814;
wire   [7:0] max_V_248_fu_620_p3;
reg   [7:0] max_V_248_reg_819;
reg    ap_condition_exit_pp0_iter6_stage0;
wire    src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_ready;
wire   [7:0] src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_return;
wire    src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350_ap_ready;
wire    src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_ready;
wire   [7:0] ap_phi_reg_pp0_iter0_arrayidx396_i179246_load_0_2_reg_298;
reg   [7:0] ap_phi_reg_pp0_iter1_arrayidx396_i179246_load_0_2_reg_298;
reg   [7:0] ap_phi_reg_pp0_iter2_arrayidx396_i179246_load_0_2_reg_298;
reg   [7:0] ap_phi_reg_pp0_iter3_arrayidx396_i179246_load_0_2_reg_298;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_0_0_reg_310;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_0_0_reg_310;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_0_0_reg_310;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_0_0_reg_310;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_0_0_reg_310;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_2_reg_321;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_2_reg_321;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_2_reg_321;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_2_reg_321;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_2_reg_321;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_1_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_1_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_1_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_1_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_1_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter5_buf_cop_V_1_reg_333;
wire   [63:0] zext_ln573_4_fu_431_p1;
wire   [63:0] zext_ln573_fu_437_p1;
wire   [63:0] zext_ln1795_fu_443_p1;
reg   [12:0] col_V_fu_92;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_col_V_7;
wire   [12:0] col_V_8_fu_414_p2;
reg   [7:0] ret_125_fu_96;
reg   [7:0] ret_126_fu_100;
reg   [7:0] ret_127_fu_104;
reg   [7:0] ret_128_fu_108;
reg   [7:0] ret_129_fu_112;
reg   [7:0] ret_130_fu_116;
reg    ap_block_pp0_stage0_01001;
wire   [13:0] zext_ln1057_9_fu_404_p1;
wire   [15:0] zext_ln1057_fu_400_p1;
wire   [7:0] ret_fu_482_p3;
wire   [0:0] icmp_ln1065_fu_489_p2;
wire   [7:0] max_V_242_fu_495_p3;
wire   [0:0] icmp_ln1065_48_fu_503_p2;
wire   [7:0] select_ln56_fu_509_p3;
wire   [0:0] icmp_ln1065_49_fu_540_p2;
wire   [7:0] max_V_244_fu_545_p3;
wire   [0:0] icmp_ln1065_50_fu_552_p2;
wire   [7:0] max_V_246_fu_588_p3;
wire   [0:0] icmp_ln1065_52_fu_593_p2;
wire   [7:0] select_ln56_4_fu_599_p3;
wire   [7:0] max_V_247_fu_607_p3;
wire   [0:0] icmp_ln1065_53_fu_614_p2;
wire   [0:0] icmp_ln1065_54_fu_637_p2;
wire   [7:0] select_ln56_6_fu_641_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_350;
reg    ap_condition_337;
reg    ap_condition_61;
reg    ap_condition_339;
reg    ap_condition_672;
reg    ap_condition_675;
reg    ap_condition_679;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

reversi_accel_xfExtractPixels_1_1_0_s src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344(
    .ap_ready(src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter4_buf_cop_V_0_0_reg_310),
    .ap_return(src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_return)
);

reversi_accel_xfExtractPixels_1_1_0_s src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350(
    .ap_ready(src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter4_buf_cop_V_2_reg_321),
    .ap_return(src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350_ap_return)
);

reversi_accel_xfExtractPixels_1_1_0_s src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356(
    .ap_ready(src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter5_buf_cop_V_1_reg_333),
    .ap_return(src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_return)
);

reversi_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U353(
    .din0(buf_V_0_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(trunc_ln4),
    .dout(buf_cop_V_0_fu_454_p5)
);

reversi_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U354(
    .din0(buf_V_0_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(trunc_ln136_6),
    .dout(tmp_fu_465_p5)
);

reversi_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter6_stage0)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_337)) begin
        if ((1'b1 == ap_condition_350)) begin
            ap_phi_reg_pp0_iter1_arrayidx396_i179246_load_0_2_reg_298 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_arrayidx396_i179246_load_0_2_reg_298 <= ap_phi_reg_pp0_iter0_arrayidx396_i179246_load_0_2_reg_298;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_337)) begin
        if (((icmp_ln1057_fu_408_p2 == 1'd1) & (icmp_ln1057_62_fu_420_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_0_0_reg_310 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_0_0_reg_310 <= ap_phi_reg_pp0_iter0_buf_cop_V_0_0_reg_310;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_337)) begin
        if (((icmp_ln1057_fu_408_p2 == 1'd1) & (icmp_ln1057_62_fu_420_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_1_reg_333 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_1_reg_333 <= ap_phi_reg_pp0_iter0_buf_cop_V_1_reg_333;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_337)) begin
        if (((icmp_ln1057_fu_408_p2 == 1'd1) & (icmp_ln1057_62_fu_420_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_2_reg_321 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_2_reg_321 <= ap_phi_reg_pp0_iter0_buf_cop_V_2_reg_321;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_339)) begin
        if ((1'b1 == ap_condition_61)) begin
            ap_phi_reg_pp0_iter2_arrayidx396_i179246_load_0_2_reg_298 <= mat_lap_4242_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_arrayidx396_i179246_load_0_2_reg_298 <= ap_phi_reg_pp0_iter1_arrayidx396_i179246_load_0_2_reg_298;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln1057_62_reg_753_pp0_iter2_reg == 1'd1) & (icmp_ln1057_reg_749_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_0_0_reg_310 <= buf_cop_V_0_fu_454_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_0_0_reg_310 <= ap_phi_reg_pp0_iter3_buf_cop_V_0_0_reg_310;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln1057_62_reg_753_pp0_iter2_reg == 1'd1) & (icmp_ln1057_reg_749_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_1_reg_333 <= tmp_fu_465_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_1_reg_333 <= ap_phi_reg_pp0_iter3_buf_cop_V_1_reg_333;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln1057_62_reg_753_pp0_iter2_reg == 1'd1) & (icmp_ln1057_reg_749_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_2_reg_321 <= ap_phi_reg_pp0_iter3_arrayidx396_i179246_load_0_2_reg_298;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_buf_cop_V_2_reg_321 <= ap_phi_reg_pp0_iter3_buf_cop_V_2_reg_321;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1057_fu_408_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_V_fu_92 <= col_V_8_fu_414_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_V_fu_92 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_125_fu_96 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter3_reg == 1'd1))) begin
            ret_125_fu_96 <= ret_129_fu_112;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_126_fu_100 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter4_reg == 1'd1))) begin
            ret_126_fu_100 <= ret_130_fu_116;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_127_fu_104 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter5_reg == 1'd1))) begin
            ret_127_fu_104 <= ret_128_fu_108;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_128_fu_108 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter5_reg == 1'd1))) begin
            ret_128_fu_108 <= src_buf_V_2_1_reg_791_pp0_iter5_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_129_fu_112 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter3_reg == 1'd1))) begin
            ret_129_fu_112 <= src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_130_fu_116 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter4_reg == 1'd1))) begin
            ret_130_fu_116 <= src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        col_V_7_reg_741 <= ap_sig_allocacmp_col_V_7;
        col_V_7_reg_741_pp0_iter1_reg <= col_V_7_reg_741;
        icmp_ln1057_62_reg_753_pp0_iter1_reg <= icmp_ln1057_62_reg_753;
        icmp_ln1057_reg_749 <= icmp_ln1057_fu_408_p2;
        icmp_ln1057_reg_749_pp0_iter1_reg <= icmp_ln1057_reg_749;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln1057_62_reg_753_pp0_iter2_reg <= icmp_ln1057_62_reg_753_pp0_iter1_reg;
        icmp_ln1057_reg_749_pp0_iter2_reg <= icmp_ln1057_reg_749_pp0_iter1_reg;
        icmp_ln1057_reg_749_pp0_iter3_reg <= icmp_ln1057_reg_749_pp0_iter2_reg;
        icmp_ln1057_reg_749_pp0_iter4_reg <= icmp_ln1057_reg_749_pp0_iter3_reg;
        icmp_ln1057_reg_749_pp0_iter5_reg <= icmp_ln1057_reg_749_pp0_iter4_reg;
        icmp_ln1061_reg_777_pp0_iter3_reg <= icmp_ln1061_reg_777;
        icmp_ln1061_reg_777_pp0_iter4_reg <= icmp_ln1061_reg_777_pp0_iter3_reg;
        icmp_ln1061_reg_777_pp0_iter5_reg <= icmp_ln1061_reg_777_pp0_iter4_reg;
        icmp_ln1061_reg_777_pp0_iter6_reg <= icmp_ln1061_reg_777_pp0_iter5_reg;
        src_buf_V_2_1_reg_791_pp0_iter5_reg <= src_buf_V_2_1_reg_791;
        src_buf_V_2_1_reg_791_pp0_iter6_reg <= src_buf_V_2_1_reg_791_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_buf_cop_V_0_0_reg_310 <= ap_phi_reg_pp0_iter1_buf_cop_V_0_0_reg_310;
        ap_phi_reg_pp0_iter2_buf_cop_V_1_reg_333 <= ap_phi_reg_pp0_iter1_buf_cop_V_1_reg_333;
        ap_phi_reg_pp0_iter2_buf_cop_V_2_reg_321 <= ap_phi_reg_pp0_iter1_buf_cop_V_2_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_arrayidx396_i179246_load_0_2_reg_298 <= ap_phi_reg_pp0_iter2_arrayidx396_i179246_load_0_2_reg_298;
        ap_phi_reg_pp0_iter3_buf_cop_V_0_0_reg_310 <= ap_phi_reg_pp0_iter2_buf_cop_V_0_0_reg_310;
        ap_phi_reg_pp0_iter3_buf_cop_V_1_reg_333 <= ap_phi_reg_pp0_iter2_buf_cop_V_1_reg_333;
        ap_phi_reg_pp0_iter3_buf_cop_V_2_reg_321 <= ap_phi_reg_pp0_iter2_buf_cop_V_2_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_buf_cop_V_1_reg_333 <= ap_phi_reg_pp0_iter4_buf_cop_V_1_reg_333;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_fu_408_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1057_62_reg_753 <= icmp_ln1057_62_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1057_reg_749_pp0_iter1_reg == 1'd1))) begin
        icmp_ln1061_reg_777 <= icmp_ln1061_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1057_reg_749_pp0_iter4_reg == 1'd1))) begin
        icmp_ln1065_51_reg_814 <= icmp_ln1065_51_fu_566_p2;
        max_V_245_reg_809 <= max_V_245_fu_558_p3;
        src_buf_V_1_1_reg_804 <= src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1057_reg_749_pp0_iter3_reg == 1'd1))) begin
        max_V_243_reg_798 <= max_V_243_fu_517_p3;
        src_buf_V_2_1_reg_791 <= src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_350_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1057_reg_749_pp0_iter5_reg == 1'd1))) begin
        max_V_248_reg_819 <= max_V_248_fu_620_p3;
    end
end

always @ (*) begin
    if (((icmp_ln1057_fu_408_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1057_reg_749_pp0_iter5_reg == 1'd0))) begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_V_7 = 13'd0;
    end else begin
        ap_sig_allocacmp_col_V_7 = col_V_fu_92;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_672)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_0_address1 = zext_ln573_fu_437_p1;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_0_address1 = zext_ln573_4_fu_431_p1;
        end else begin
            buf_V_0_address1 = 'bx;
        end
    end else begin
        buf_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_V_0_ce0 = 1'b1;
    end else begin
        buf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_0_ce1 = 1'b1;
    end else begin
        buf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_672)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_0_d1 = mat_lap_4242_dout;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_0_d1 = 8'd0;
        end else begin
            buf_V_0_d1 = 'bx;
        end
    end else begin
        buf_V_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_0_we1 = 1'b1;
    end else begin
        buf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_675)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_1_address1 = zext_ln573_fu_437_p1;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_1_address1 = zext_ln573_4_fu_431_p1;
        end else begin
            buf_V_1_address1 = 'bx;
        end
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_675)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_1_d1 = mat_lap_4242_dout;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_1_d1 = 8'd0;
        end else begin
            buf_V_1_d1 = 'bx;
        end
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_679)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_2_address1 = zext_ln573_fu_437_p1;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_2_address1 = zext_ln573_4_fu_431_p1;
        end else begin
            buf_V_2_address1 = 'bx;
        end
    end else begin
        buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln_read_reg_707 == 2'd0) & ~(trunc_ln_read_reg_707 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln_read_reg_707 == 2'd0) & ~(trunc_ln_read_reg_707 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_679)) begin
        if ((cmp_i_i115_i == 1'd1)) begin
            buf_V_2_d1 = mat_lap_4242_dout;
        end else if ((cmp_i_i115_i_read_reg_703 == 1'd0)) begin
            buf_V_2_d1 = 8'd0;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln_read_reg_707 == 2'd0) & ~(trunc_ln_read_reg_707 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln_read_reg_707 == 2'd0) & ~(trunc_ln_read_reg_707 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i115_i_read_reg_703 == 1'd0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        mat_dil_b_4243_blk_n = mat_dil_b_4243_full_n;
    end else begin
        mat_dil_b_4243_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        mat_dil_b_4243_write = 1'b1;
    end else begin
        mat_dil_b_4243_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op67_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_lap_4242_blk_n = mat_lap_4242_empty_n;
    end else begin
        mat_lap_4242_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op67_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_lap_4242_read = 1'b1;
    end else begin
        mat_lap_4242_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (mat_dil_b_4243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op67_read_state2 == 1'b1) & (mat_lap_4242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (mat_dil_b_4243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op67_read_state2 == 1'b1) & (mat_lap_4242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (mat_dil_b_4243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op67_read_state2 == 1'b1) & (mat_lap_4242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op67_read_state2 == 1'b1) & (mat_lap_4242_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = ((icmp_ln1061_reg_777_pp0_iter6_reg == 1'd0) & (mat_dil_b_4243_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_337 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_339 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_350 = ((icmp_ln1057_fu_408_p2 == 1'd1) & (icmp_ln1057_62_fu_420_p2 == 1'd1) & (cmp_i_i115_i_read_read_fu_120_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_61 = ((cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1));
end

always @ (*) begin
    ap_condition_672 = ((1'b0 == ap_block_pp0_stage0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_675 = ((1'b0 == ap_block_pp0_stage0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln_read_reg_707 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_679 = (~(trunc_ln_read_reg_707 == 2'd0) & ~(trunc_ln_read_reg_707 == 2'd1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_arrayidx396_i179246_load_0_2_reg_298 = 'bx;

assign ap_phi_reg_pp0_iter0_buf_cop_V_0_0_reg_310 = 'bx;

assign ap_phi_reg_pp0_iter0_buf_cop_V_1_reg_333 = 'bx;

assign ap_phi_reg_pp0_iter0_buf_cop_V_2_reg_321 = 'bx;

always @ (*) begin
    ap_predicate_op67_read_state2 = ((cmp_i_i115_i == 1'd1) & (icmp_ln1057_62_reg_753 == 1'd1) & (icmp_ln1057_reg_749 == 1'd1));
end

assign buf_V_0_address0 = zext_ln1795_fu_443_p1;

assign buf_V_1_address0 = zext_ln1795_fu_443_p1;

assign buf_V_2_address0 = zext_ln1795_fu_443_p1;

assign cmp_i_i115_i_read_read_fu_120_p2 = cmp_i_i115_i;

assign cmp_i_i115_i_read_reg_703 = cmp_i_i115_i;

assign col_V_8_fu_414_p2 = (ap_sig_allocacmp_col_V_7 + 13'd1);

assign icmp_ln1057_62_fu_420_p2 = ((zext_ln1057_fu_400_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_408_p2 = ((zext_ln1057_9_fu_404_p1 < add_ln1795) ? 1'b1 : 1'b0);

assign icmp_ln1061_fu_449_p2 = ((col_V_7_reg_741_pp0_iter1_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln1065_48_fu_503_p2 = ((src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_return > max_V_242_fu_495_p3) ? 1'b1 : 1'b0);

assign icmp_ln1065_49_fu_540_p2 = ((ret_126_fu_100 > max_V_243_reg_798) ? 1'b1 : 1'b0);

assign icmp_ln1065_50_fu_552_p2 = ((ret_130_fu_116 > max_V_244_fu_545_p3) ? 1'b1 : 1'b0);

assign icmp_ln1065_51_fu_566_p2 = ((src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_356_ap_return > max_V_245_fu_558_p3) ? 1'b1 : 1'b0);

assign icmp_ln1065_52_fu_593_p2 = ((ret_127_fu_104 > max_V_246_fu_588_p3) ? 1'b1 : 1'b0);

assign icmp_ln1065_53_fu_614_p2 = ((ret_128_fu_108 > max_V_247_fu_607_p3) ? 1'b1 : 1'b0);

assign icmp_ln1065_54_fu_637_p2 = ((src_buf_V_2_1_reg_791_pp0_iter6_reg > max_V_248_reg_819) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_489_p2 = ((ret_129_fu_112 > ret_fu_482_p3) ? 1'b1 : 1'b0);

assign mat_dil_b_4243_din = ((p_read8[0:0] == 1'b1) ? select_ln56_6_fu_641_p3 : max_V_248_reg_819);

assign max_V_242_fu_495_p3 = ((icmp_ln1065_fu_489_p2[0:0] == 1'b1) ? ret_129_fu_112 : ret_fu_482_p3);

assign max_V_243_fu_517_p3 = ((p_read2[0:0] == 1'b1) ? select_ln56_fu_509_p3 : max_V_242_fu_495_p3);

assign max_V_244_fu_545_p3 = ((icmp_ln1065_49_fu_540_p2[0:0] == 1'b1) ? ret_126_fu_100 : max_V_243_reg_798);

assign max_V_245_fu_558_p3 = ((icmp_ln1065_50_fu_552_p2[0:0] == 1'b1) ? ret_130_fu_116 : max_V_244_fu_545_p3);

assign max_V_246_fu_588_p3 = ((icmp_ln1065_51_reg_814[0:0] == 1'b1) ? src_buf_V_1_1_reg_804 : max_V_245_reg_809);

assign max_V_247_fu_607_p3 = ((p_read6[0:0] == 1'b1) ? select_ln56_4_fu_599_p3 : max_V_246_fu_588_p3);

assign max_V_248_fu_620_p3 = ((icmp_ln1065_53_fu_614_p2[0:0] == 1'b1) ? ret_128_fu_108 : max_V_247_fu_607_p3);

assign p_read_1_reg_721 = p_read8;

assign p_read_2_reg_726 = p_read6;

assign p_read_3_reg_731 = p_read2;

assign ret_fu_482_p3 = ((p_read[0:0] == 1'b1) ? ret_125_fu_96 : 8'd0);

assign select_ln56_4_fu_599_p3 = ((icmp_ln1065_52_fu_593_p2[0:0] == 1'b1) ? ret_127_fu_104 : max_V_246_fu_588_p3);

assign select_ln56_6_fu_641_p3 = ((icmp_ln1065_54_fu_637_p2[0:0] == 1'b1) ? src_buf_V_2_1_reg_791_pp0_iter6_reg : max_V_248_reg_819);

assign select_ln56_fu_509_p3 = ((icmp_ln1065_48_fu_503_p2[0:0] == 1'b1) ? src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_344_ap_return : max_V_242_fu_495_p3);

assign trunc_ln_read_reg_707 = trunc_ln;

assign zext_ln1057_9_fu_404_p1 = ap_sig_allocacmp_col_V_7;

assign zext_ln1057_fu_400_p1 = ap_sig_allocacmp_col_V_7;

assign zext_ln1795_fu_443_p1 = col_V_7_reg_741_pp0_iter1_reg;

assign zext_ln573_4_fu_431_p1 = col_V_7_reg_741;

assign zext_ln573_fu_437_p1 = col_V_7_reg_741;

endmodule //reversi_accel_xfdilate_1024_1024_1_0_1_0_1025_3_3_Pipeline_Col_Loop
