// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module overlay_control_overlay_control_Pipeline_VITIS_LOOP_14_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_TVALID,
        src_TDATA,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        axis_data_V_7_out,
        axis_data_V_7_out_ap_vld,
        axis_keep_V_5_out,
        axis_keep_V_5_out_ap_vld,
        axis_strb_V_5_out,
        axis_strb_V_5_out_ap_vld,
        axis_last_V_5_out,
        axis_last_V_5_out_ap_vld,
        axis_id_V_5_out,
        axis_id_V_5_out_ap_vld,
        axis_dest_V_5_out,
        axis_dest_V_5_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
input  [23:0] src_TDATA;
output   src_TREADY;
input  [2:0] src_TKEEP;
input  [2:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [23:0] axis_data_V_7_out;
output   axis_data_V_7_out_ap_vld;
output  [2:0] axis_keep_V_5_out;
output   axis_keep_V_5_out_ap_vld;
output  [2:0] axis_strb_V_5_out;
output   axis_strb_V_5_out_ap_vld;
output  [0:0] axis_last_V_5_out;
output   axis_last_V_5_out_ap_vld;
output  [0:0] axis_id_V_5_out;
output   axis_id_V_5_out_ap_vld;
output  [0:0] axis_dest_V_5_out;
output   axis_dest_V_5_out_ap_vld;

reg ap_idle;
reg src_TREADY;
reg axis_data_V_7_out_ap_vld;
reg axis_keep_V_5_out_ap_vld;
reg axis_strb_V_5_out_ap_vld;
reg axis_last_V_5_out_ap_vld;
reg axis_id_V_5_out_ap_vld;
reg axis_dest_V_5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] axis_user_V_fu_131_p1;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    src_TDATA_blk_n;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_loop_init;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

overlay_control_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if (((src_TVALID == 1'b0) | (ap_start_int == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_data_V_7_out_ap_vld = 1'b1;
    end else begin
        axis_data_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_dest_V_5_out_ap_vld = 1'b1;
    end else begin
        axis_dest_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_id_V_5_out_ap_vld = 1'b1;
    end else begin
        axis_id_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_keep_V_5_out_ap_vld = 1'b1;
    end else begin
        axis_keep_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_last_V_5_out_ap_vld = 1'b1;
    end else begin
        axis_last_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (axis_user_V_fu_131_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        axis_strb_V_5_out_ap_vld = 1'b1;
    end else begin
        axis_strb_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        src_TDATA_blk_n = src_TVALID;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((src_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_TREADY = 1'b1;
    end else begin
        src_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((src_TVALID == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign axis_data_V_7_out = src_TDATA;

assign axis_dest_V_5_out = src_TDEST;

assign axis_id_V_5_out = src_TID;

assign axis_keep_V_5_out = src_TKEEP;

assign axis_last_V_5_out = src_TLAST;

assign axis_strb_V_5_out = src_TSTRB;

assign axis_user_V_fu_131_p1 = src_TUSER;

endmodule //overlay_control_overlay_control_Pipeline_VITIS_LOOP_14_1
